### PR TITLE
Make remember_device account specific (Fixed specs)

### PR DESCRIPTION
**Pull request by MikeRogers0**
Follow up to #59 except with the specs broken in the PR fixed. // @Gasparila / @vargasx 

That said, currently `master`is failing for:

```
rspec ./spec/controllers/devise_authy_controller_spec.rb:32 # Devise::DeviseAuthyController POST #verify_authy Should login the user if token is ok
rspec ./spec/controllers/devise_authy_controller_spec.rb:46 # Devise::DeviseAuthyController POST #verify_authy Should set remember_device if selected
rspec ./spec/controllers/devise_authy_controller_spec.rb:211 # Devise::DeviseAuthyController POST #verify_authy_installation Should enable authy for user
rspec ./spec/controllers/devise_authy_controller_spec.rb:235 # Devise::DeviseAuthyController POST #request_sms Should send sms if user is logged
rspec ./spec/features/authy_authenticatable_spec.rb:28 # Authy Authenticatable If user has two factor authentication Sign in should succeed
rspec ./spec/features/authy_authenticatable_spec.rb:84 # Authy Authenticatable If user has two factor authentication Click link Request sms
```

### CODE REVIEW

**Comment by Gasparila** [comment]
@vargasx Any chance of merging this? @MikeRogers0 looks like there's some merge conflicts

**Comment by MikeRogers0** [comment]
@Gasparila Merge conflicts fixed (I removed the changes to the version number) :)
@vargasx Any dice?

**Comment by vargasx** [comment]
@MikeRogers0 it looks good, thank you :). I'll testing this looking for merge.

**Comment by Gasparila** [comment]
Any update on this? I would love to get back on Authy master

**Comment by MikeRogers0** [comment]
Thank you @senekis !

**Pull request merged**
