### PR TITLE
Form args

### PR DESCRIPTION
**Pull request by thejchap**
Allow button and form to take options hash

### CODE REVIEW

**Comment by thejchap** [comment]
Is everything ok with this PR?

**Comment by shaneog** [comment]
:+1:

**Comment by whatbird** [comment]
awesome, i was going to do this

:+1: :shipit:

**Comment by taglia** [comment]
This is great, why is the PR not merged yet?

**Comment by caseywatts** [comment]
I was just about to implement this too lol
I don't want to fork this gem / use a fork if I can help it.

@danpal is there anything I can do to help you review this /or/ could I PR a smaller chunk of this that's more clearly/easily merged?
I'm most interested in the `authy_request_sms_link(opts={})` part so I don't have to style it based on `id`.

**Comment by caseywatts** [comment]
In the meantime, we're deciding whether to:
1. fork the gem to merge this PR to use, or 
2. monkey-patch it in an initializer

In case it helps someone else, here's our monkey-patch option, in `config/initializers/authy.rb`
```
#We're re-opening Gem internals here to add options. This is based on this PR
#https://github.com/authy/authy-devise/pull/33
#Which as of 11/17/15 remains unmerged
#We may fork the gem
#So check the gemfile
DeviseAuthy::Views::Helpers.module_eval do
  def authy_request_sms_link(opts={})
    opts = {
      :id => "authy-request-sms-link",
      :method => :post,
      :remote => true
    }.merge(opts)

    link_to(
      I18n.t('request_sms', {:scope => 'devise'}),
      url_for([resource_name, :request_sms]),
      opts
    )
  end
end
```

**Comment by senekis** [comment]
@thejchap Thanks a lot for the pull request. :smiley: 

It was merged in the next-release branch, so It's going to be in our next version of the gem.

**Pull request closed without merging**
