### PR TITLE
Make remember_device account specific

### PR DESCRIPTION
**Pull request by Gasparila**
Fixes https://github.com/authy/authy-devise/issues/58

### CODE REVIEW

**Comment by MikeRogers0** [comment]
Anyone able to merge this? This seems like a fairly important PR.

**Comment by vargasx** [comment]
@Gasparila nice work, could you please take a look a specs, when I run them I see this error `no implicit conversion of nil into String`, could you add a test for the new behavior ?

**Comment by Gasparila** [comment]
Hi Vargasx,

It is working fine in production for use so we will keep it as is. The tests are probably failing because https://github.com/authy/authy-devise/pull/59/files#diff-504e05fb0907b711490ad2748668bd2cR26 assumes the cookie exists. In our experience, however, this cookie is never blank

**Comment by MikeRogers0** [comment]
I'm happy to fork `flexport:master` and fix the test if you want @Gasparila @vargasx ?

**Comment by vargasx** [comment]
@MikeRogers0 that would be great cc @Gasparila

**Comment by Gasparila** [comment]
Closing in favor of https://github.com/authy/authy-devise/pull/67

**Pull request closed without merging**
