### PR TITLE
Stop Devise from bypassing 2fa

### PR DESCRIPTION
**Pull request by Gasparila**
Fix for https://github.com/authy/authy-devise/issues/69

### CODE REVIEW

**Comment by segantii-alex-falkowski** [comment]
Any idea when this can be merged and published. This seems to be a critical bug.

**Comment by Gasparila** [comment]
@senekis Can this be merged? It's a pretty big issue

**Comment by senekis** [comment]
@Gasparila thanks!, I'm reviewing it.

**Comment by segantii-alex-falkowski** [comment]
Thank you please advise when released as a gem.

**Comment by senekis** [comment]
@segantii-alex-falkowski I released the gem today, check https://rubygems.org/gems/devise-authy/versions/1.8.1

**Pull request merged**
